info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - 首页
  /user/CreateUser:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: passwd
        type: string
      - description: 再次输入密码
        in: formData
        name: rePasswd
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: code
      summary: Create new user
      tags:
      - service/UserServices
  /user/DeleteUser:
    post:
      consumes:
      - application/json
      parameters:
      - description: 要删除的用户id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: code
      summary: delete user by id
      tags:
      - service/UserServices
  /user/UpdateUser:
    post:
      consumes:
      - application/json
      parameters:
      - description: 要修改的用户id
        in: query
        name: id
        type: string
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: passwd
        type: string
      - description: 用户邮箱
        in: query
        name: email
        type: string
      - description: 用户手机号
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: code
      summary: update user by id
      tags:
      - service/UserServices
  /user/UserLogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: passwd
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: code
      summary: user login
      tags:
      - service/UserServices
  /user/getUserLists:
    get:
      consumes:
      - application/json
      description: get user list from mysql
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: code
      summary: GetUserLists
      tags:
      - service/UserServices
swagger: "2.0"
